FROM anibali/pytorch:cuda-9.0
WORKDIR /home/johmathe/
RUN conda install jupyter
RUN conda install -c conda-forge matplotlib
RUN conda install -c conda-forge ipywidgets
USER root
CMD ["/home/user/miniconda/envs/py36/bin/jupyter", "notebook", "--allow-root", "--ip=0.0.0.0"]
